### ISSUE TITLE
Не активная кнопка "сохранить"

### ISSUE THREAD

**Issue by megoRU** [levelsranks/levels-ranks-web#13]
0 реакции на кнопку сохранить.

![image](https://user-images.githubusercontent.com/23276305/63712320-2e34f800-c846-11e9-8123-dcf336fd4602.png)

В чем мб проблема?

**Comment by M0st1ce** [comment]
В данный момент, кнопка "Сохранить" не работает, не подключена функция. Всё будет работать в следующей версии панели администратора.

**Comment by megoRU** [comment]
Понял.
