### ISSUE TITLE
PHP 8.0.10 - Deprecated: Required parameter $update_claimed_id

### ISSUE THREAD

**Issue by MrKlarki** [levelsranks/levels-ranks-web#141]
Hello. For php version 8.0.10 it gives me errors
Deprecated: Required parameter $update_claimed_id follows optional parameter $method in /www/wwwroot/site.com/system/classes/openid.class.php on line 190

Deprecated: Required parameter $update_claimed_id follows optional parameter $method in /www/wwwroot/site.com/system/classes/openid.class.php on line 320

**Comment by FlamesONE** [comment]
But it's not LR WEB script
