### ISSUE TITLE
web interface do not work correctly after update

### ISSUE THREAD

**Issue by tridochko** [levelsranks/levels-ranks-web#143]
Использую связку NGINX + php-fpm + mysql
Всё работало стабильно на ubuntu 16.04 LTS. Обновился до 20.04 LTS. В процессе обновился php-fpm 7.0 -> 7.4 Базу не трогал. 
На главной странице: в блоке Рейтинг игроков ничего не отображается. Блок с сервером работает и отображается корректно. Блок с мини-статистикой отображается корректно и со значениями. 
При переходе в сайдбаре: "Статистика игроков", получаю ошибку 404. URL вида https://my_site/?page=toppoints&server_group=0.
Rankstats загружается, показывает название сервера, но в остальном пустая.
На странице статистики игрока всё чуть сложнее. Скриншот:
![lvl_rank](https://user-images.githubusercontent.com/62173462/133244603-b6f20e71-9b22-4e18-adb5-acc83fa8699e.png)

Мне бы понять, это я что-то не доставил или не донастроил, или код сайта под текущую связку не подходит.

**Comment by tridochko** [comment]
В логах nginx ничего интересного не нашёл, кроме такой ругани:

*3147 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type bool in /var/www/new/app/modules/module_page_profiles/ext/Player.php on line 345PHP message: PHP Notice:  Trying to access ar
ray offset on value of type bool in /var/www/new/app/modules/module_page_profiles/ext/Player.php on line 345

PHP message: PHP Warning:  Division by zero in /var/www/new/app/modules/module_page_profiles/forward/interface.php on line 173

PHP message: PHP Notice:  Undefined offset: 0 in /var/www/new/app/modules/module_page_profiles/forward/interface.php on line 200PHP message: PHP Notice:  Trying
to access array offset on value of type null in /var/www/new/app/modules/module_page_profiles/forward/interface.php on line 200PHP message: PHP Notice:  Undefined offset: 1 in /var/www/new/app/modules/module_page_profiles/forward/interface.php on line 200PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/new/app/modules/module_page_profiles/forward/interface.php on line 200PHP message: PHP Notice:  Undefined offset: 2 in /var/www/new/app/modules/module_page_profiles/forward/interface.php on line 200

**Comment by FlamesONE** [comment]
Поменялось не только ядро, но и модули. Все модули были адаптированы под новое ядро, и раз у тебя есть ?page, значит у тебя старое. Решение - обновить модули.

**Comment by tridochko** [comment]
удалил всё через rm -rf
Склонировал гитом альфа бранч отсюда, залил на сервер, прошёл процедуру установки. В результате снова получилось что-то похожее, хотя симптомы местами отличаются.

Теперь при переходе на персональную страницу статистики, а так же при переходе на станицу "статистика игроков" получаю сообщение "009|Страница не существует"

В логах такое месиво:

2021/09/14 08:23:07 [error] 129340#129340: *6 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /var/www/new/app/modules/module_block_main_stats/forward/data.php on line 22" while reading response header from upstream, client: 185.163.156.201, serv
er: my_site, request: "GET /new/home/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my_site", referrer: "https://my_site/new/profiles/76561197980574272/0/?search=1/"
2021/09/14 08:23:08 [error] 129340#129340: *51 FastCGI sent in stderr: "PHP message: PHP Notice:  Only variables should be passed by reference in /var/www/new/app/modules/module_block_main_servers_monitoring/ext/ServerInfo.php on line 84" while reading response header fro
m upstream, client: 185.163.156.201, server: my_site, request: "POST /new/app/modules/module_block_main_servers_monitoring/includes/js_controller.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my_site", referrer: "https://my_site/new/home/"
2021/09/14 08:23:11 [error] 129340#129340: *51 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /var/www/new/app/modules/module_block_main_stats/forward/data.php on line 22" while reading response header from upstream, client: 185.163.156.201, ser
ver: my_site, request: "GET /new/home/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my_site", referrer: "https://my_site/new/profiles/76561197980574272/0/?search=1/"
2021/09/14 08:23:57 [error] 129340#129340: *58 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: SB_admins_import in /var/www/new/app/modules/module_page_adminpanel/includes/general.php on line 109" while reading response header from upstream, client: 18
5.163.156.201, server: my_site, request: "GET /new/adminpanel/?new/adminpanel/=&section=general&options=module_block_main_servers_monitoring HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my_site", referrer: "https://my_site/new/adminpanel/?new/ad
minpanel/=&section=stats&options=module_block_main_servers_monitoring"
2021/09/14 08:24:23 [error] 129340#129340: *58 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: SB_admins_import in /var/www/new/app/modules/module_page_adminpanel/includes/general.php on line 109" while reading response header from upstream, client: 18
5.163.156.201, server: my_site, request: "GET /new/adminpanel/?new/adminpanel/=&section=general&options=module_block_main_servers_monitoring HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my_site", referrer: "https://my_site/new/adminpanel/?new/ad
minpanel/=&section=modules&options=module_block_main_servers_monitoring"
2021/09/14 08:24:31 [error] 129340#129340: *58 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: SB_admins_import in /var/www/new/app/modules/module_page_adminpanel/includes/general.php on line 109" while reading response header from upstream, client: 18
5.163.156.201, server: my_site, request: "GET /new/adminpanel/?new/adminpanel/=&section=general&options=module_block_main_servers_monitoring HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my_site", referrer: "https://my_site/new/adminpanel/?new/ad
minpanel/=&section=general&options=module_block_main_servers_monitoring"
2021/09/14 08:25:18 [error] 129340#129340: *81 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /var/www/new/app/modules/module_block_main_stats/forward/data.php on line 22" while reading response header from upstream, client: 185.163.156.201, ser
ver: my_site, request: "GET /new/home/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my_site", referrer: "https://my_site/new/adminpanel/?new/adminpanel/&section=modules&options=module_block_main_stats"
2021/09/14 08:25:19 [error] 129340#129340: *82 FastCGI sent in stderr: "PHP message: PHP Notice:  Only variables should be passed by reference in /var/www/new/app/modules/module_block_main_servers_monitoring/ext/ServerInfo.php on line 84" while reading response header fro
m upstream, client: 185.163.156.201, server: my_site, request: "POST /new/app/modules/module_block_main_servers_monitoring/includes/js_controller.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my_site", referrer: "https://my_site/new/home/"
2021/09/14 08:25:21 [error] 129340#129340: *82 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type bool in /var/www/new/app/modules/module_page_toppoints/forward/data.php on line 80" while reading response header from upstream
, client: 185.163.156.201, server: my_site, request: "GET /new/toppoints HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my_site", referrer: "https://my_site/new/home/"

Ну и до этого, хотябы модуль мини статистики показывал цифры. Сейчас показывает нули.

**Comment by tridochko** [comment]
С нулями справился - неверно префикс указал. Ну, теперь я всё обновил, но получаю те же ошибки.

**Comment by tridochko** [comment]
![lvl_rank_2](https://user-images.githubusercontent.com/62173462/133265122-1a2b0b3c-1dbd-4216-9710-a9dfd84902b1.png)

Как ни кручу rewrite - страница https://my_site/toppoints всёравно превращается в https://my_site/?page=toppoints&server_group=0 и показывает 404 ошибку.

**Comment by tridochko** [comment]
Разобрался с проблемой. С php 5.4 и свежим nginx заработало нормально.
