### ISSUE TITLE
What to enter if I used SQLite database??

### ISSUE THREAD

**Issue by brdasma** [levelsranks/levels-ranks-web#155]
I used a SQLite database in the downloading process of level ranks.
That means that I didn't specify a database. So what do I fill out here?
![image](https://user-images.githubusercontent.com/92693717/158042828-8f070faa-d070-4fda-8909-21272572a16a.png)

**Comment by FlamesONE** [comment]
you url must be **http://site.com/**
without GET params. ?test=param, or something

**Comment by brdasma** [comment]
> you url must be **http://site.com/** without GET params. ?test=param, or something

What?

**Comment by brdasma** [comment]
> you url must be **http://site.com/** without GET params. ?test=param, or something

I switched to another db. This problem is solved now.

I do have another question tho. What do I write in the "Table" field?
