### ISSUE TITLE
Кеш иконок

### ISSUE THREAD

**Issue by megoRU** [levelsranks/levels-ranks-web#16]
Нет иконки со стима. Когда открываешь то загружается

![image](https://user-images.githubusercontent.com/23276305/64120794-d8140780-cda5-11e9-957a-447f4d04c5c9.png)

![image](https://user-images.githubusercontent.com/23276305/64120856-0396f200-cda6-11e9-9555-5393b5824d6b.png)

**Comment by M0st1ce** [comment]
У вас старый файл /storage/cache/sessions/options.php.
Вероятнее всего вы просто поверх прошлой версии поставили новую и не проходили установщик.
Удалите storage/cache/sessions/options.php и пройдите установщик.

**Comment by megoRU** [comment]
спасибо
