### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Denis-Raev** [levelsranks/levels-ranks-web#164]
Hi all! When installing LR Web, at the stage of specifying the STEAM_ID of the administrator, when clicking on the "Check" button, it does not go any further (the field with the entered SteamID is simply cleared). What could be? PHP 8 (tried also on 7.4 - same problem).

The web server logs are empty. The chrome console says this:
https://ibb.co/BZNkyX3

**Comment by russh3l** [comment]
hello, how did you fix it?

i have the same problem

**Comment by AleksandrPe** [comment]
I couldn't fix it, so I bypassed this step by adding my data to the table.
![image](https://user-images.githubusercontent.com/45788713/215991918-46a652d9-2ca9-473a-9ad9-a628598f235e.png)
