### ISSUE TITLE
Как вернуть админ панель

### ISSUE THREAD

**Issue by megoRU** [levelsranks/levels-ranks-web#17]
если случайно выключил

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/64267912-e138dc00-cf3f-11e9-8a99-8facaf909846.png)

**Comment by sapsanDev** [comment]
Заходим в папку **storage/cache/sessions** и удаляем файл **modules_initialization.php**
Далее заходим в папку модуля админ панели **app/modules/module_page_adminpanel**
И меняем 12 строку на **"status": "1"** после открываем админ панель

**Comment by megoRU** [comment]
у меня status 1 и так стоит. А то что удалить файл **modules_initialization.php** не помогло

**Comment by M0st1ce** [comment]
Пожалуйста, чтобы не засорять GitHub, попрошу писать о всех проблемах в Discord канал, вам ответят там в разы быстрее и разобраться будет проще.
