### ISSUE TITLE
Предложение подробной информации по Steam

### ISSUE THREAD

**Issue by statebyte** [levelsranks/levels-ranks-web#20]
Предлагаю добавить блок со Steam32 сюды:
![image](https://user-images.githubusercontent.com/29007593/65811128-813ef980-e1bc-11e9-90a8-2fa70a544212.png)
Чтобы можно было быстро скопировать его в нудные системы :)

**Comment by theeldarka** [comment]
Зачем он там? 0_о, игрокам это не нужно

**Comment by HolyHender** [comment]
steamid.xyz в помощь

**Comment by statebyte** [comment]
> Зачем он там? 0_о, игрокам это не нужно
Ну тут как бы, я не говорил что это нужно для игроков :)
> steamid.xyz в помощь
Он так и есть в запросе, просто сюды вывести и усё для админа)

**Comment by HolyHender** [comment]
ну такое

**Comment by statebyte** [comment]
![image](https://user-images.githubusercontent.com/29007593/72977673-05f5f900-3de6-11ea-8439-d90e2313a0d9.png)
Опа, а всё же им нужно это :)

**Comment by fr0nch** [comment]
Показ не настроить, надо плагин чтобы был, а его вроде как нет.
