### ISSUE TITLE
web interface not working

### ISSUE THREAD

**Issue by shubhamdev8** [levelsranks/levels-ranks-web#23]
i pasted the web files to my subdomain root directory but its not working
this is the error apache server  shows
[Sun Oct 13 01:27:01.461436 2019] [php7:error] [pid 3192] [client 43.230.107.75:1605] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function app\\ext\\General::__construct(), 0 passed in /var/www/rank/index.php on line 113 and exactly 1 expected in /var/www/rank/app/ext/General.php:39\nStack trace:\n#0 /var/www/rank/index.php(113): app\\ext\\General->__construct()\n#1 {main}\n  thrown in /var/www/rank/app/ext/General.php on line 39

**Comment by M0st1ce** [comment]
Fixed
