### ISSUE TITLE
cant add sourcebans mod

### ISSUE THREAD

**Issue by shubhamdev8** [levelsranks/levels-ranks-web#24]
when try to add sourcebans mod it gives me a blank page of error
![image](https://user-images.githubusercontent.com/52833233/66717768-672b2b00-edfa-11e9-868d-fa70af51fc44.png)
apache server error log-
[Sun Oct 13 20:47:02.655389 2019] [php7:error] [pid 522] [client 43.230.106.111:2800] PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/rank/app/modules/module_page_adminpanel/ext/Admin.php:141\nStack trace:\n#0 /var/www/rank/app/modules/module_page_adminpanel/forward/data.php(45): Admin->action_db_add_mods()\n#1 /var/www/rank/app/ext/Graphics.php(31): require('/var/www/rank/a...')\n#2 /var/www/rank/index.php(134): app\\ext\\Graphics->__construct(Object(app\\ext\\General), Object(app\\ext\\Modules), Object(app\\ext\\Db), Object(app\\ext\\Auth), Object(app\\ext\\Notifications))\n#3 {main}\n  thrown in /var/www/rank/app/modules/module_page_adminpanel/ext/Admin.php on line 141, referer: http://rank.mysticgaming.tk/?page=adminpanel&section=db

**Comment by Steammers** [comment]
add this in db.php

```
'SourceBans' => 
                [0 => 
                   [
                   'HOST' => 'Хост SB / MA',
		   'PORT' => '3306',
                   'USER' => 'Логин SB / MA',
                   'PASS' => 'Пароль SB / MA',
                   'DB'   => [0 => 
                                 [
                                 'DB'     => 'Имя базы данных SB / MA',
                                 'Prefix' => [0 => 
                                                 [
                                                 'table' => 'sb_',
                                                 'name'  => 'SourceBans',
                                                 'mod' => '730 / 240 / 215',
                                                 'steam' => '1 / 0'
                                                 ],
                                             ],
                                 ],
                             ],
                   ],
               ],
```

**Comment by shubhamdev8** [comment]
thanks it worked :)
