### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Joez252** [levelsranks/levels-ranks-web#26]
How i can install this ? Some eng instructions ?

**Comment by d0kt0r** [comment]
There is a choice of English

**Comment by Joez252** [comment]
> There is a choice of English

But idk how to install or ?

**Comment by M0st1ce** [comment]
If you do not see instructions in English, what is the problem in 2019 year to open translator?

**Comment by Joez252** [comment]
![ooffffffff](https://user-images.githubusercontent.com/56035421/68077153-0a9aaa80-fdbf-11e9-83b0-9c62c8398f98.png)
But idk how to install.
Тут нечего делать, я не знаю, как трахаться.
Вы понимаете или как это написать еще.
