### ISSUE TITLE
Исправления показа рангов в профиле игрока

### ISSUE THREAD

**Issue by domikuss** [levelsranks/levels-ranks-web#5]
https://github.com/levelsranks/levels-ranks-web/blob/2b6f0a6cb043c1c0ad53d62441ae5380fc75523a/web_dev/app/modules/module_page_profiles/forward/interface.php#L304
Нужно изменить $General->arr_general на $Player->found[  $Player->server_group  ]
Иначе будет вот такое
![Скриншот](https://user-images.githubusercontent.com/52104782/62000452-5535c800-b0e8-11e9-82d1-54b03ea3e987.png)

**Comment by M0st1ce** [comment]
Fixed
