### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by shubhamdev8** [levelsranks/levels-ranks-web#57]
I am getting a error 500 on my apache server
logs:
[Sat Dec 28 12:38:23.353697 2019] [proxy_fcgi:error] [pid 4588] [client 146.196.39.193:64224] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '?' in /home/stats/public_html/app/ext/Db.php on line 193\n'

**Comment by fr0nch** [comment]
Have you enabled abbreviated tags in your php settings?

**Comment by shubhamdev8** [comment]
![image](https://user-images.githubusercontent.com/52833233/71543484-55890680-2999-11ea-81ba-f136b43d2a0e.png)
its on default

**Comment by theeldarka** [comment]
php > 7.0

**Comment by shubhamdev8** [comment]
I have php 7.0 and 7.1 installed

**Comment by shubhamdev8** [comment]
My Bad, I am using virtualmin with multiple php versions and it was using older version by default
thanks for your help :)

**Comment by Hibari233** [comment]
> My Bad, I am using virtualmin with multiple php versions and it was using older version by default
> thanks for your help :)

I got the same problem like yours . But I do not have multiple php version . I only have a version which is php 7.2. But the site shows HTTP 500 ERROR again. Do you have any suggestions?

**Comment by Hibari233** [comment]
Here's the error log.
***********************************
[Wed Feb 05 15:18:07.248091 2020] [php7:warn] [pid 1107] [client 61.167.169.2:7327] PHP Warning:  sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/app/ext/Db.php on line 130
**************************************************************
[Wed Feb 05 15:18:07.251101 2020] [php7:error] [pid 1107] [client 61.167.169.2:7327] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /var/www/html/app/ext/Db.php:263\nStack trace:\n#0 /var/www/html/app/ext/Db.php(330): app\\ext\\Db->inquiry('Core', 0, 0, 'SELECT * FROM l...', Array)\n#1 /var/www/html/app/ext/General.php(180): app\\ext\\Db->queryAll('Core', 0, 0, 'SELECT * FROM l...')\n#2 /var/www/html/app/ext/General.php(59): app\\ext\\General->get_server_list()\n#3 /var/www/html/index.php(137): app\\ext\\General->__construct(Object(app\\ext\\Db))\n#4 {main}\n  thrown in /var/www/html/app/ext/Db.php on line 263
*******************************************************

**Comment by shubhamdev8** [comment]
> Here's the error log.
> 
> [Wed Feb 05 15:18:07.248091 2020] [php7:warn] [pid 1107] [client 61.167.169.2:7327] PHP Warning: sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/app/ext/Db.php on line 130
> 
> [Wed Feb 05 15:18:07.251101 2020] [php7:error] [pid 1107] [client 61.167.169.2:7327] PHP Fatal error: Uncaught Error: Call to a member function prepare() on null in /var/www/html/app/ext/Db.php:263\nStack trace:\n#0 /var/www/html/app/ext/Db.php(330): app\ext\Db->inquiry('Core', 0, 0, 'SELECT * FROM l...', Array)\n#1 /var/www/html/app/ext/General.php(180): app\ext\Db->queryAll('Core', 0, 0, 'SELECT * FROM l...')\n#2 /var/www/html/app/ext/General.php(59): app\ext\General->get_server_list()\n#3 /var/www/html/index.php(137): app\ext\General->__construct(Object(app\ext\Db))\n#4 {main}\n thrown in /var/www/html/app/ext/Db.php on line 263

i think your db is not configured properly
check /storage/cache/sessions/db.php if its properly configured or not
and make sure you have installed all the required php modules

**Comment by Hibari233** [comment]
> Here's the error log.
> [Wed Feb 05 15:18:07.248091 2020] [php7:warn] [pid 1107] [client 61.167.169.2:7327] PHP Warning: sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/app/ext/Db.php on line 130
> [Wed Feb 05 15:18:07.251101 2020] [php7:error] [pid 1107] [client 61.167.169.2:7327] PHP Fatal error: Uncaught Error: Call to a member function prepare() on null in /var/www/html/app/ext/Db.php:263\nStack trace:\n#0 /var/www/html/app/ext/Db.php(330): app\ext\Db->inquiry('Core', 0, 0, 'SELECT * FROM l...', Array)\n#1 /var/www/html/app/ext/General.php(180): app\ext\Db->queryAll('Core', 0, 0, 'SELECT * FROM l...')\n#2 /var/www/html/app/ext/General.php(59): app\ext\General->get_server_list()\n#3 /var/www/html/index.php(137): app\ext\General->__construct(Object(app\ext\Db))\n#4 {main}\n thrown in /var/www/html/app/ext/Db.php on line 263
> 
> i think your db is not configured properly
> check /storage/cache/sessions/db.php if its properly configured or not
> and make sure you have installed all the required php modules

I did not configure the db.php . The instructions on GitHub did not say to configure the db.php. What I only did is configure the Apache , PHP and MariaDB, and put the web in /var/www/. Then the web told me that I need to configure the databases and it can be found in databases.cfg. So how to configure the db.php? I am very sorry to spend your time. Thank you very much.

**Comment by Hibari233** [comment]
> Here's the error log.
> [Wed Feb 05 15:18:07.248091 2020] [php7:warn] [pid 1107] [client 61.167.169.2:7327] PHP Warning: sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/app/ext/Db.php on line 130
> [Wed Feb 05 15:18:07.251101 2020] [php7:error] [pid 1107] [client 61.167.169.2:7327] PHP Fatal error: Uncaught Error: Call to a member function prepare() on null in /var/www/html/app/ext/Db.php:263\nStack trace:\n#0 /var/www/html/app/ext/Db.php(330): app\ext\Db->inquiry('Core', 0, 0, 'SELECT * FROM l...', Array)\n#1 /var/www/html/app/ext/General.php(180): app\ext\Db->queryAll('Core', 0, 0, 'SELECT * FROM l...')\n#2 /var/www/html/app/ext/General.php(59): app\ext\General->get_server_list()\n#3 /var/www/html/index.php(137): app\ext\General->__construct(Object(app\ext\Db))\n#4 {main}\n thrown in /var/www/html/app/ext/Db.php on line 263
> 
> i think your db is not configured properly
> check /storage/cache/sessions/db.php if its properly configured or not
> and make sure you have installed all the required php modules

I found the db.php's template and I have installed the Levels-Ranks core in my CSGO server.
But I didn't know the database configuration.
I use the command "mysql -uroot -A" and "show databases;". But I found there is no databases at all;
I could not find the Core's databases, maybe it is default ?
Would I need to create the databases and tables manually and configure the db.php with the databases?
Can you describe it more in details?
Thank you for helping me!

**Comment by shubhamdev8** [comment]
> > Here's the error log.
> > [Wed Feb 05 15:18:07.248091 2020] [php7:warn] [pid 1107] [client 61.167.169.2:7327] PHP Warning: sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/app/ext/Db.php on line 130
> > [Wed Feb 05 15:18:07.251101 2020] [php7:error] [pid 1107] [client 61.167.169.2:7327] PHP Fatal error: Uncaught Error: Call to a member function prepare() on null in /var/www/html/app/ext/Db.php:263\nStack trace:\n#0 /var/www/html/app/ext/Db.php(330): app\ext\Db->inquiry('Core', 0, 0, 'SELECT * FROM l...', Array)\n#1 /var/www/html/app/ext/General.php(180): app\ext\Db->queryAll('Core', 0, 0, 'SELECT * FROM l...')\n#2 /var/www/html/app/ext/General.php(59): app\ext\General->get_server_list()\n#3 /var/www/html/index.php(137): app\ext\General->__construct(Object(app\ext\Db))\n#4 {main}\n thrown in /var/www/html/app/ext/Db.php on line 263
> > i think your db is not configured properly
> > check /storage/cache/sessions/db.php if its properly configured or not
> > and make sure you have installed all the required php modules
> 
> I found the db.php's template and I have installed the Levels-Ranks core in my CSGO server.
> But I didn't know the database configuration.
> I use the command "mysql -uroot -A" and "show databases;". But I found there is no databases at all;
> I could not find the Core's databases, maybe it is default ?
> Would I need to create the databases and tables manually and configure the db.php with the databases?
> Can you describe it more in details?
> Thank you for helping me!

add me on discord FLASHING#8548
