### ISSUE TITLE
CSS и JS

### ISSUE THREAD

**Issue by CrazyHackGUT** [levelsranks/levels-ranks-web#6]
Сейчас подгрузка стилей и скриптов сделана очень странно: вместо обычных CSS/JS файлов (которые имеют свойство кэшироваться, тем самым ускоряя последующие загрузки), они встраиваются пыхокодом (см. [пример](https://github.com/levelsranks/levels-ranks-web/tree/alpha/modules/module_block_main_servers_monitoring/assets)) в зависимости от неких настроек - в страницу, из-за чего одни и тот же блок постоянно передаётся по Сети вместо того, чтобы осесть в кэше браузера.

В связи с этим, предлагаю вместо явного "хардкодинга" этого контента **раскидать все стили по файлам по-человечески**. Браузер сможет кэшировать контент как минимум. А чтобы избавиться от условий - для каждой настройки свой отдельный CSS-файл.

Ну и раз уж зашла речь о стилях и скриптах...
Очень странно выглядит, что JS - не минифицирован (пример по ссылке выше), отдаётся на браузеры и публикуется в целом "as is", а CSS - минифицирован (пример там же).
Предлагаю так же загрузить в репозиторий оригинальные CSS-файлы без минификации, а JS наоборот минифицировать.

Предлагаемые мною изменения сократят время повторной загрузки любой страницы, поскольку браузер сможет и будет кэшировать JS + CSS.

**Comment by M0st1ce** [comment]
Реализовано.
