### ISSUE TITLE
how to enable shadow

### ISSUE THREAD

**Issue by shubhamdev8** [levelsranks/levels-ranks-web#67]
![unknown](https://user-images.githubusercontent.com/52833233/72429259-8cdb1e00-37b5-11ea-923b-f3f8934dd0b3.png)
how to enablw title shadows like this

**Comment by theeldarka** [comment]
example.com/storage/cache/sessions/options.php

Change 'badge_type' => 2

Save file

**Comment by shubhamdev8** [comment]
thank you
