### ISSUE TITLE
[feature request] add default image to non existing maps images

### ISSUE THREAD

**Issue by z4cH3r** [levelsranks/levels-ranks-web#8]
just like the sourcebans does 
![image](https://user-images.githubusercontent.com/31113638/62837135-8a0f5680-bc74-11e9-8b1e-f32f257c8905.png)

what i'm talking about
![image](https://user-images.githubusercontent.com/31113638/62837137-909dce00-bc74-11e9-96e8-15ee1d1cde06.png)

**Comment by M0st1ce** [comment]
fixed
