### ISSUE TITLE
[module_block_main_servers_monitoring] Stops displaying the next servers' status when one is unavailable

### ISSUE THREAD

**Issue by mgeerse** [levelsranks/levels-ranks-web#81]
The module_block_main_servers_monitoring stops rendering the next servers in the list when one server is downed.

Example of all servers showing (expected functionality):
[Working normally](https://image.prntscr.com/image/TB2giG_WQzyIPZ7o5cb46A.png)

Example of one server down, the rest not showing:
[Bad behaviour](https://image.prntscr.com/image/3xc-6Sk2Rvu3ReS4n171Lw.png)

Expected behavior:
If a server is down, display the next servers status regardless.

**Comment by SkyBadPT** [comment]
I have the same problem!

**Comment by Hibari233** [comment]
I have the same problem! Please fix it! Thanks!

**Comment by ZUBAT** [comment]
Fixed on #82
